# Generated by Django 4.2 on 2024-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutprosecution',
            old_name='article_ar',
            new_name='article_arb',
        ),
        migrations.RenameField(
            model_name='aboutprosecution',
            old_name='article_en',
            new_name='article_eng',
        ),
        migrations.RenameField(
            model_name='aboutprosecution',
            old_name='title_ar',
            new_name='title_arb',
        ),
        migrations.RenameField(
            model_name='aboutprosecution',
            old_name='title_en',
            new_name='title_eng',
        ),
        migrations.RenameField(
            model_name='attorneygeneral',
            old_name='article_ar',
            new_name='article_arb',
        ),
        migrations.RenameField(
            model_name='attorneygeneral',
            old_name='article_en',
            new_name='article_eng',
        ),
        migrations.RenameField(
            model_name='attorneygeneral',
            old_name='name_ar',
            new_name='name_arb',
        ),
        migrations.RenameField(
            model_name='attorneygeneral',
            old_name='name_en',
            new_name='name_eng',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='article_ar',
            new_name='article_arb',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='article_en',
            new_name='article_eng',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.AddField(
            model_name='news',
            name='title_arb',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_eng',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
