# Generated by Django 5.0.3 on 2024-03-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_rename_article_ar_aboutprosecution_article_arb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to=''),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
