# Generated by Django 5.0.3 on 2024-03-17 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_remove_news_video_alter_image_image_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='attached_image',
        ),
        migrations.RemoveField(
            model_name='attorneygeneral',
            name='image',
        ),
        migrations.AddField(
            model_name='attorneygeneral',
            name='main_image',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default=True, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='news',
            name='video',
            field=models.ManyToManyField(blank=True, to='News.video'),
        ),
    ]
