# Generated by Django 4.2 on 2024-02-28 16:44

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_number', models.BigIntegerField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comment', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prosecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arb', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_arb', models.CharField(max_length=255)),
                ('name_eng', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_number', models.BigIntegerField(editable=False, unique=True)),
                ('complainant_name', models.CharField(max_length=255)),
                ('complainant_address', models.CharField(max_length=255)),
                ('complainant_nationality', django_countries.fields.CountryField(max_length=2)),
                ('complainant_national_number', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('complainant_passport_type', models.CharField(blank=True, max_length=50, null=True)),
                ('complainant_passport_number', models.CharField(blank=True, max_length=255, null=True)),
                ('complainant_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('complainant_phone', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('accused_name', models.CharField(max_length=255)),
                ('report_number', models.CharField(blank=True, max_length=255, null=True)),
                ('police', models.CharField(blank=True, max_length=255, null=True)),
                ('date_report', models.DateField(blank=True, default=None, null=True)),
                ('Materials_of_accusation', models.CharField(blank=True, max_length=255, null=True)),
                ('summary_report', models.TextField(max_length=300)),
                ('note', models.TextField(blank=True, max_length=300, null=True)),
                ('prosecution', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='Reports.prosecution')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Reports.state')),
            ],
        ),
        migrations.AddField(
            model_name='prosecution',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reports.state'),
        ),
    ]
