# Generated by Django 5.0.3 on 2024-03-10 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports', '0002_alter_reports_complainant_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='Materials_of_accusation',
            new_name='materials_of_accusation',
        ),
    ]
